require("../node_modules/bootstrap/dist/css/bootstrap.min.css");
require("../resources/styles/css/reset.css");
require("../node_modules/animate.css/animate.min.css");
// require('../node_modules/components-font-awesome/css/fontawesome.min.css');

require('../bower_components/components-font-awesome/css/font-awesome.min.css');
require('../bower_components/angular-ui-tree/dist/angular-ui-tree.min.css');
require('../bower_components/ui-select/dist/select.min.css');
require('../node_modules/angular-ui-bootstrap/dist/ui-bootstrap-csp.css');
require("../node_modules/gumga-login/dist/gumga-login.min.css");
require("../resources/styles/css/gumga/gumga.min.css");
require("../gumga-layout/gumga-layout.min.css");
require('../bower_components/grands-components/grands-components.min.css');
require('../bower_components/characteristic-front/characteristic.min.css');
require('../bower_components/buddy-person-front/buddypersonfront.min.css');
require('../bower_components/product-front/product.min.css');
require('../bower_components/operationtype-front/operationtype.min.css');
require('../bower_components/tributador-front/tributador.min.css');
require('../bower_components/movementgroup-front/movementgroup.min.css');
require('../resources/javascript/ng-color-picker/color-picker.css');
require('../bower_components/sweetalert/dist/sweetalert.css');