import 'jquery';
import 'jquery-ui-bundle';
import 'angular';
import '@uirouter/angularjs';
import '@uirouter/angularjs/release/stateEvents';

import '@mobiage/base/dist/mobiage-base.min.js';
import '@mobiage/base/dist/mobiage-base.min.css';
import '@mobiage/login/dist/mobiage-login.min.js';
import '@mobiage/login/dist/mobiage-login.min.css';

require('script-loader!../node_modules/jquery/dist/jquery.min.js');
require('script-loader!../node_modules/angular-mocks/angular-mocks');
require('script-loader!../node_modules/angular-ui-bootstrap/dist/ui-bootstrap-tpls');
require('script-loader!../bower_components/ui-select/dist/select.min.js');
require('script-loader!../node_modules/angular-sanitize/angular-sanitize.min');
require('script-loader!../bower_components/sweetalert/dist/sweetalert.min.js');
require('script-loader!../bower_components/ngSweetAlert/SweetAlert.min.js');
require('script-loader!../node_modules/bootstrap/dist/js/bootstrap.min');
require('script-loader!../resources/javascript/ng-color-picker/color-picker.js');
require('script-loader!../node_modules/es5-shim/es5-shim.min');
require('script-loader!../node_modules/angular-datepicker/dist/index.js');
require('script-loader!../resources/javascript/bootstrap-notify.min');
require('script-loader!../node_modules/mousetrap/mousetrap.min');
require('script-loader!../bower_components/angular-ui-tree/dist/angular-ui-tree.js');
require('script-loader!../node_modules/ng-img-crop/compile/minified/ng-img-crop');
require('script-loader!../node_modules/moment/min/moment.min');
require('script-loader!../gumga-layout/gumga-layout.min');
require('script-loader!../node_modules/gumga-login/dist/gumga-login.min');
require('script-loader!../i18n/angular-locale_pt-br');
require('script-loader!../node_modules/moment-timezone/builds/moment-timezone-with-data.min');
require('script-loader!../node_modules/gumga-rest-ng/dist/gumga-rest.min');
require('script-loader!../node_modules/gumga-controller-ng/dist/gumga-controller.min');
require('script-loader!../node_modules/gumga-alert-ng/dist/gumga-alert.min');
require('script-loader!../node_modules/gumga-web-storage-ng/dist/gumga-web-storage.min');
require('script-loader!../node_modules/gumga-many-to-one-ng/dist/gumga-many-to-one.min');
require('script-loader!../node_modules/gumga-address-ng/dist/gumga-address.min');
require('script-loader!../node_modules/gumga-translate-ng/dist/gumga-translate.min');
require('script-loader!../node_modules/gumga-mask-ng/dist/gumga-mask.min');
require('script-loader!../node_modules/gumga-upload-ng/dist/gumga-upload.min');
require('script-loader!../node_modules/gumga-custom-fields-ng/dist/gumga-custom-fields.min');
require('script-loader!../node_modules/gumga-form-buttons-ng/dist/gumga-form-buttons.min');
require('script-loader!../node_modules/gumga-counter-ng/dist/gumga-counter.min');
require('script-loader!../node_modules/gumga-breadcrumb/dist/gumga-breadcrumb.min');
require('script-loader!../node_modules/gumga-confirm/dist/gumga-confirm.min');
require('script-loader!../node_modules/gumga-one-to-many-ng/dist/gumga-one-to-many.min');
require('script-loader!../node_modules/gumga-populate-ng/dist/gumga-populate.min');
require('script-loader!../node_modules/gumga-many-to-many-ng/dist/gumga-many-to-many.min');
require('script-loader!../node_modules/gumga-form-ng/dist/gumga-form.min');
require('script-loader!../node_modules/gumga-generic-filter-ng/dist/gumga-generic-filter.min');
require('script-loader!../node_modules/gumga-query-filter-ng/dist/gumga-query-filter.min');
require('script-loader!../node_modules/gumga-list-ng/dist/gumga-list.min');
require('script-loader!../node_modules/gumga-gquery-ng/dist/gumga-gquery.min');
require('script-loader!../node_modules/gumga-date-ng/dist/gumga-date.min');
require('script-loader!../node_modules/gumga-query-action-ng/dist/gumga-query-action.min');
require('script-loader!../node_modules/gumga-number-in-words-ng/dist/gumga-number-in-words.min');
require('script-loader!../node_modules/my-account-embedded/dist/my-profile-embedded.min');
require('script-loader!../node_modules/gumga-gallery-icon-ng/dist/gumga-gallery-icon.min');
require('script-loader!../node_modules/gumga-chips-ng/dist/gumga-chips.min');
require('script-loader!../resources/javascript/ng-filters-br/ng-filter-br.js');
require('script-loader!../bower_components/gumga-avatar-ng/dist/gumga-avatar.min.js');
require('script-loader!../bower_components/angular-ui-sortable/sortable.min.js');

require('script-loader!../bower_components/ace-builds/src-min-noconflict/ace');
require('script-loader!../bower_components/ace-builds/src-min-noconflict/mode-markdown');
require('script-loader!../bower_components/ace-builds/src-min-noconflict/ext-language_tools');
require('script-loader!../bower_components/angular-ui-ace/ui-ace.min.js');
